spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/socialapp
spring.datasource.username=postgres
spring.datasource.password=06012005003561
spring.jpa.hibernate.ddl-auto=update
jwt.secret=OLsdgnongwogweoooi322orp2poOSEGuoiogwp2pog2pigpPIO4ig3npg3wpg3g

server.port=8080